version: '3.7'

services:
  master:
    image: clusterio
    volumes:
      - auth-secret:/factorioClusterio/secret-api-token.txt
    ports:
      - 8080:8080


  world1:
    image: clusterio
    volumes:
      - ./world1/config.json:/factorioClusterio/config.json:ro
      - /srv/clusterio/instances/world1:/factorioClusterio/instances/world1
      - auth-secret:/factorioClusterio/secret-api-token.txt:ro
    environment:
      - INSTANCE=world1
      - FACTORIOPORT=34197
    ports:
      - 34197:34197/udp

  world2:
    image: clusterio
    volumes:
      - ./world2/config.json:/factorioClusterio/config.json:ro
      - /srv/clusterio/instances/world2:/factorioClusterio/instances/world2
      - auth-secret:/factorioClusterio/secret-api-token.txt:ro
    environment:
      - INSTANCE=world2
      - FACTORIOPORT=34198
    ports:
      - 34198:34198/udp

volumes:
  auth-secret:
