version: '3.7'

services:
  master:
    image: clust-master
    volumes:
      - auth-secret:/factorioClusterio/secret
    environment:
      - SECRET_API_TOKEN_FILE=/factorioClusterio/secret/secret-api-token.txt
      - VIRTUAL_HOST=master.gamequest.dk
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=master.gamequest.dk
      - LETSENCRYPT_EMAIL=abondoa@gmail.com
    networks:
      - reverse_proxy
      - default
    env_file:
      - master.env
    ports:
      - 8080:8080

  world1:
    image: clust-slave
    volumes:
      - ./instances/world1:/factorioClusterio/instances/world1
      - ./sharedMods:/factorioClusterio/sharedMods:ro
      - ./sharedPlugins:/factorioClusterio/sharedPlugins:ro
      - auth-secret:/factorioClusterio/secret:ro
    environment:
      - INSTANCE=world1
      - FACTORIOPORT=34197
      - SECRET_API_TOKEN_FILE=/factorioClusterio/secret/secret-api-token.txt
      - MASTERIP=master
    env_file:
      - .env
    ports:
      - 34197:34197/udp
    depends_on: 
      - master

  world2:
    image: clust-slave
    volumes:
      - ./instances/world2:/factorioClusterio/instances/world2
      - ./sharedMods:/factorioClusterio/sharedMods:ro
      - ./sharedPlugins:/factorioClusterio/sharedPlugins:ro
      - auth-secret:/factorioClusterio/secret:ro
    environment:
      - INSTANCE=world2
      - FACTORIOPORT=34198
      - SECRET_API_TOKEN_FILE=/factorioClusterio/secret/secret-api-token.txt
      - MASTERIP=master
    env_file:
      - .env
    ports:
      - 34198:34198/udp
    depends_on: 
      - master

volumes:
  auth-secret:

networks:
  reverse_proxy:
    external:
      name: reverse_proxy

